export * from "./professor.routes"
export * from "./question.routes"
// export * from "./ranking.routes"
export * from "./student.routes"
export * from "./test.routes"
export * from "./upload.routes"
export * from "./download.routes"