export * from "./professor.controller"
export * from "./question.controller"
// export * from "./ranking.controller"
export * from "./student.controller"
export * from "./test.controller"
export * from "./upload.controller"
export * from "./download.controller"